import React, { useState, useEffect } from 'react'
import {
  Box,
  Typography,
  Button,
  TextField,
  FormControlLabel,
  Switch,
  CircularProgress,
  Alert,
  AppBar,
  Toolbar,
  IconButton,
  Divider,
  Chip,
  Tabs,
  Tab,
} from '@mui/material'
import { ArrowBack, Save } from '@mui/icons-material'
import { useNavigate, useParams, useLocation } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { useDocumentTitle } from '../../hooks/useDocumentTitle'
import { postsAPI } from '../../services/api'
import type { CreatePostRequest, UpdatePostRequest, Tag } from '../../services/api'
import TagInput from '../../components/TagInput'
import PostFileUploader from '../../components/PostFileUploader'
import MDEditor from '@uiw/react-md-editor'
import '@uiw/react-md-editor/markdown-editor.css'
import AdminNavbar from '../../components/AdminNavbar'

const PostEditorPage: React.FC = () => {
  const { isAuthenticated } = useAuth()
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const location = useLocation()
  
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string>('')
  const [success, setSuccess] = useState<string>('')
  const [rightPanelTab, setRightPanelTab] = useState(0)
  const [post, setPost] = useState({
    title: '',
    content: '',
    summary: '',
    slug: '',
    published: false,
    tags: [] as Tag[],
  })

  const isEditing = Boolean(id && id !== 'new')
  const pageTitle = isEditing ? 'Edit Post' : 'Create New Post'
  useDocumentTitle(pageTitle)

  // Function to generate slug from title
  const generateSlugFromTitle = (title: string): string => {
    return title
      .toLowerCase()
      .replace(/[^\w\s-]/g, '') // Remove special characters
      .replace(/\s+/g, '-') // Replace spaces with hyphens
      .replace(/-+/g, '-') // Replace multiple hyphens with single
      .replace(/^-+|-+$/g, '') // Trim hyphens from start and end
      .substring(0, 100) // Limit length
  }

  // Redirect if not authenticated
  useEffect(() => {
    if (!isAuthenticated) {
      navigate('/login')
    }
  }, [isAuthenticated, navigate])

  // Load post data if editing
  useEffect(() => {
    const loadPost = async () => {
      if (isEditing && id) {
        try {
          setLoading(true)
          const response = await postsAPI.getAdminPost(parseInt(id))
          const postData = response.data
          setPost({
            title: postData.title,
            content: postData.content,
            summary: postData.summary,
            slug: postData.slug,
            published: postData.published,
            tags: postData.tags || [],
          })
        } catch (err) {
          console.error('Error loading post:', err)
          setError('Failed to load post')
        } finally {
          setLoading(false)
        }
      }
    }

    if (isAuthenticated) {
      loadPost()
    }
  }, [isAuthenticated, isEditing, id])

  const handleSave = async () => {
    try {
      setSaving(true)
      setError('')
      setSuccess('')

      if (isEditing && id) {
        const updateData: UpdatePostRequest = {
          title: post.title,
          content: post.content,
          summary: post.summary,
          slug: post.slug || undefined,
          published: post.published,
          tag_ids: post.tags.map(tag => tag.id),
        }
        await postsAPI.updatePost(parseInt(id), updateData)
        setSuccess('Post updated successfully!')
      } else {
        const createData: CreatePostRequest = {
          title: post.title,
          content: post.content,
          summary: post.summary,
          slug: post.slug || undefined,
          published: post.published,
          tag_ids: post.tags.map(tag => tag.id),
        }
        const response = await postsAPI.createPost(createData)
        setSuccess('Post created successfully!')
        
        // Navigate to edit mode for the newly created post
        if (response.data?.id) {
          navigate(`/admin/posts/${response.data.id}`, { replace: true })
        }
      }
    } catch (err) {
      console.error('Error saving post:', err)
      setError('Failed to save post')
    } finally {
      setSaving(false)
    }
  }

  const handleBack = () => {
    // Check if we're on an admin route
    const isAdminRoute = location.pathname.startsWith('/admin')
    if (isAdminRoute) {
      navigate('/admin/posts')
    } else {
      navigate('/admin') // fallback
    }
  }

  const handleFieldChange = (field: string, value: string | boolean | Tag[]) => {
    if (field === 'title' && typeof value === 'string') {
      // Auto-generate slug when title changes (only for new posts or if slug is empty)
      const autoGeneratedSlug = generateSlugFromTitle(value)
      setPost(prev => ({ 
        ...prev, 
        [field]: value,
        // Only auto-generate slug if it's a new post or if current slug matches the old title's generated slug
        slug: (!isEditing || prev.slug === '' || prev.slug === generateSlugFromTitle(prev.title)) 
          ? autoGeneratedSlug 
          : prev.slug
      }))
    } else {
      setPost(prev => ({ ...prev, [field]: value }))
    }
  }

  const handleGenerateSlug = () => {
    const autoSlug = generateSlugFromTitle(post.title)
    setPost(prev => ({ ...prev, slug: autoSlug }))
  }

  if (!isAuthenticated) {
    return null
  }

  if (loading) {
    const isAdminRoute = location.pathname.startsWith('/admin')
    return (
      <Box>
        {isAdminRoute && <AdminNavbar />}
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="400px">
          <CircularProgress />
        </Box>
      </Box>
    )
  }

  const isAdminRoute = location.pathname.startsWith('/admin')

  return (
    <Box sx={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
      {isAdminRoute ? (
        <AdminNavbar />
      ) : (
        <AppBar position="static" color="default" elevation={1}>
          <Toolbar>
            <IconButton
              edge="start"
              onClick={handleBack}
              sx={{ mr: 2 }}
            >
              <ArrowBack />
            </IconButton>
            
            <Typography variant="h6" sx={{ flexGrow: 1 }}>
              {pageTitle}
            </Typography>
            
            <Button
              variant="contained"
              startIcon={<Save />}
              onClick={handleSave}
              disabled={saving || !post.title.trim() || !post.content.trim()}
            >
              {saving ? 'Saving...' : (isEditing ? 'Update' : 'Create')}
            </Button>
          </Toolbar>
        </AppBar>
      )}

      {/* Content */}
      <Box sx={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        {/* Page header for admin routes */}
        {isAdminRoute && (
          <Box sx={{ px: 3, py: 2, bgcolor: 'background.paper', borderBottom: '1px solid', borderColor: 'divider' }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <IconButton onClick={handleBack}>
                  <ArrowBack />
                </IconButton>
                <Typography variant="h5" component="h1">
                  {pageTitle}
                </Typography>
              </Box>
              <Button
                variant="contained"
                startIcon={<Save />}
                onClick={handleSave}
                disabled={saving || !post.title.trim() || !post.content.trim()}
                size="large"
              >
                {saving ? 'Saving...' : (isEditing ? 'Update' : 'Create')}
              </Button>
            </Box>
          </Box>
        )}

        {/* Alerts */}
        {(error || success) && (
          <Box sx={{ px: 3, pt: 2 }}>
            {error && (
              <Alert severity="error" sx={{ mb: 1 }} onClose={() => setError('')}>
                {error}
              </Alert>
            )}
            {success && (
              <Alert severity="success" sx={{ mb: 1 }} onClose={() => setSuccess('')}>
                {success}
              </Alert>
            )}
          </Box>
        )}

        {/* Split Layout: Editor (Left) + Metadata (Right) */}
        <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
          {/* Left Panel - Editor (75%) */}
          <Box sx={{ flex: '0 0 70%', display: 'flex', flexDirection: 'column', overflow: 'hidden', borderRight: '1px solid', borderColor: 'divider' }}>
            <Box sx={{ flex: 1, overflow: 'auto', p: 3 }}>
              {/* Title */}
              <TextField
                fullWidth
                label="Post Title"
                value={post.title}
                onChange={(e) => handleFieldChange('title', e.target.value)}
                placeholder="Enter your post title..."
                variant="outlined"
                sx={{ mb: 3 }}
                autoFocus
              />
              
              {/* Content Editor */}
              <Box sx={{ mb: 2 }}>
                <Typography variant="subtitle1" sx={{ mb: 1, fontWeight: 600 }}>
                  Content (Markdown)
                </Typography>
                <Box sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1, overflow: 'hidden' }}>
                  <MDEditor
                    value={post.content}
                    onChange={(value) => handleFieldChange('content', value || '')}
                    preview="edit"
                    height={600}
                    data-color-mode="light"
                  />
                </Box>
              </Box>
            </Box>
          </Box>

          {/* Right Panel - Metadata (30%) */}
          <Box sx={{ flex: '0 0 30%', display: 'flex', flexDirection: 'column', overflow: 'hidden', bgcolor: 'grey.50' }}>
            {/* Tabs Header */}
            <Box sx={{ borderBottom: 1, borderColor: 'divider', bgcolor: 'background.paper' }}>
              <Tabs 
                value={rightPanelTab} 
                onChange={(_, newValue) => setRightPanelTab(newValue)}
                variant="fullWidth"
              >
                <Tab label="Metadata" />
                <Tab label="Attachments" />
              </Tabs>
            </Box>

            {/* Tab Content */}
            <Box sx={{ flex: 1, overflow: 'auto', p: 3 }}>
              {/* Metadata Tab */}
              {rightPanelTab === 0 && (
                <Box>
                  {/* Publish Status */}
                  <Box sx={{ mb: 3, p: 2, bgcolor: 'background.paper', borderRadius: 1 }}>
                    <Typography variant="subtitle2" sx={{ mb: 1.5, fontWeight: 600 }}>
                      Status
                    </Typography>
                    <FormControlLabel
                      control={
                        <Switch
                          checked={post.published}
                          onChange={(e) => handleFieldChange('published', e.target.checked)}
                          color="primary"
                        />
                      }
                      label={
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Typography variant="body2">
                            {post.published ? 'Published' : 'Draft'}
                          </Typography>
                          <Chip 
                            label={post.published ? 'Live' : 'Draft'} 
                            size="small" 
                            color={post.published ? 'success' : 'default'}
                          />
                        </Box>
                      }
                    />
                  </Box>

                  <Divider sx={{ my: 3 }} />

                  {/* URL Slug */}
                  <Box sx={{ mb: 3 }}>
                    <Typography variant="subtitle2" sx={{ mb: 1.5, fontWeight: 600 }}>
                      URL Slug
                    </Typography>
                    <TextField
                      fullWidth
                      size="small"
                      value={post.slug}
                      onChange={(e) => handleFieldChange('slug', e.target.value)}
                      placeholder="auto-generated-slug"
                      variant="outlined"
                      helperText={post.slug ? `/posts/${post.slug}` : 'Auto-generated from title'}
                    />
                    <Button
                      size="small"
                      onClick={handleGenerateSlug}
                      disabled={!post.title.trim()}
                      sx={{ mt: 1 }}
                      fullWidth
                      variant="outlined"
                    >
                      Generate from Title
                    </Button>
                  </Box>

                  <Divider sx={{ my: 3 }} />

                  {/* Summary */}
                  <Box sx={{ mb: 3 }}>
                    <Typography variant="subtitle2" sx={{ mb: 1.5, fontWeight: 600 }}>
                      Summary
                    </Typography>
                    <TextField
                      fullWidth
                      size="small"
                      value={post.summary}
                      onChange={(e) => handleFieldChange('summary', e.target.value)}
                      placeholder="Brief description for previews..."
                      multiline
                      rows={3}
                      variant="outlined"
                      helperText="Shown in post previews and search results"
                    />
                  </Box>

                  <Divider sx={{ my: 3 }} />

                  {/* Tags */}
                  <Box>
                    <Typography variant="subtitle2" sx={{ mb: 1.5, fontWeight: 600 }}>
                      Tags
                    </Typography>
                    <TagInput
                      selectedTags={post.tags}
                      onTagsChange={(tags: Tag[]) => handleFieldChange('tags', tags)}
                      placeholder="Search or create tags..."
                      allowCreate={true}
                    />
                  </Box>
                </Box>
              )}

              {/* Attachments Tab */}
              {rightPanelTab === 1 && (
                <Box>
                  <PostFileUploader 
                    postId={isEditing && id ? parseInt(id) : null}
                  />
                </Box>
              )}
            </Box>
          </Box>
        </Box>
      </Box>
    </Box>
  )
}

export default PostEditorPage